////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /pipeline/transforms/kubernetes/
:language: en_US
:description: The Kubernetes Get transform fetches a single Kubernetes resource and writes it as an output row.

= Kubernetes Get

== Description

The *Kubernetes Get* transform fetches a single resource by kind and name, using a
xref:metadata-types/kubernetes/kubernetes-connection.adoc[Kubernetes Connection], and writes the result as an
output row. The resource is either returned as raw JSON in a single field, or as individual scalar fields.

== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Kubernetes connection|Name of the Kubernetes connection metadata to use.
|Kind|The resource kind to fetch (for example `Pod`, `Deployment`).
|Name|The name of the resource to fetch.
|Namespace|The namespace of the resource. Defaults to the connection namespace.
|Output field name|Name of the field that carries the raw resource JSON. Default `resource_manifest`.
|Output JSON|When enabled, the resource is returned as raw JSON in the output field. Otherwise selected scalar fields (`name`, `namespace`, `uid`, `creationTimestamp`) are emitted.
|===

== Related transforms

* xref:pipeline/transforms/kubernetes/kubernetes-list.adoc[Kubernetes List]
* xref:pipeline/transforms/kubernetes/kubernetes-apply.adoc[Kubernetes Apply]