////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/kubernetes/
:language: en_US
:description: The Kubernetes Scale action scales a workload to a number of replicas and optionally waits for readiness.

= Kubernetes Scale

== Description

The *Kubernetes Scale* action sets the desired replica count of a workload (Deployment, StatefulSet or
DaemonSet) using a xref:metadata-types/kubernetes/kubernetes-connection.adoc[Kubernetes Connection], and can
optionally wait until the workload reports the requested number of ready replicas.

== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Kubernetes connection|Name of the Kubernetes connection metadata to use.
|Kind|The workload kind: `Deployment`, `StatefulSet` or `DaemonSet`.
|Name|The name of the workload.
|Namespace|The namespace of the workload.
|Replicas|The desired number of replicas.
|Wait ready|When enabled, waits until the ready replicas match the requested count.
|Timeout (seconds)|Maximum time to wait for readiness before failing.
|===

== Related actions

* xref:workflow/actions/kubernetes/kubernetes-rollout.adoc[Kubernetes Rollout]
* xref:workflow/actions/kubernetes/kubernetes-apply.adoc[Kubernetes Apply]