////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
:documentationPath: /workflow/actions/kubernetes/
:language: en_US
:description: The Kubernetes Delete action deletes Kubernetes resources by name or by label selector.

= Kubernetes Delete

== Description

The *Kubernetes Delete* action deletes a Kubernetes resource by *name*, or all resources matching a *label
selector*, using a xref:metadata-types/kubernetes/kubernetes-connection.adoc[Kubernetes Connection].

When a label selector is configured, the action lists the matching resources and deletes each one. Deleting a
resource that does not exist can be ignored with the *Ignore not found* option.

== Options

[options="header", width="90%", cols="1,3"]
|===
|Option|Description
|Kubernetes connection|Name of the Kubernetes connection metadata to use.
|Kind|The resource kind to delete (for example `Pod`, `Deployment`, `Service`).
|Name|The name of the resource to delete.
|Namespace|The namespace of the resource. Defaults to the connection namespace.
|Label selector|A label selector; when set, matching resources are listed and each is deleted.
|Grace period (seconds)|Optional grace period for pod termination on delete.
|Ignore not found|When enabled, deleting a missing resource does not fail the workflow.
|===

== Related actions

* xref:workflow/actions/kubernetes/kubernetes-apply.adoc[Kubernetes Apply]
* xref:workflow/actions/kubernetes/kubernetes-scale.adoc[Kubernetes Scale]